server:
  port: 12080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    account:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/zeongit_account?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
      username: root
      password: ASDasd+-*/00
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
  main:
    allow-bean-definition-overriding: true
base:
  notUUID: 00000000000000000000000000000000
account:
  registerVerificationCodePrefix: register_verification_code:%s
  forgetVerificationCodePrefix: forget_verification_code:%s
  verificationCodeTimeout: 300000
  jwtExpiresSecond: 5184000000
  jwtSecretString: www.secdra.com
  updatePasswordTimePrefix: base:update_password_time:%s